name: Build

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        compiler: [gcc-9, gcc-10, gcc-11, clang-12, clang-13, clang-14]
        bits: [32, 64]
        lto: [LTO=y, LTO=n]

    runs-on: 'ubuntu-22.04'

    steps:
    - name: Install
      run: |
        sudo apt-get update -q
        sudo apt-get install ${{ matrix.compiler }}

    - uses: actions/checkout@v3

    - name: make
      run: |
        make CC=${{matrix.compiler}} M32=${{matrix.bits == 32 && 'y' || 'n'}} ${{matrix.lto}}
        ./extend_skl_only.sh
