name: scan-build

on: [push, pull_request]

jobs:
  scan-build:

    strategy:
      matrix:
        bits: ['32', '64']
        lto: [LTO=y, LTO=n]

    runs-on: 'ubuntu-22.04'

    steps:
    - name: Install
      run: |
        sudo apt-get update -q
        sudo apt-get install clang-tools-14

    - uses: actions/checkout@v3

    - name: make
      run: |
        scan-build-14 --status-bugs -analyze-headers make BITS=${{matrix.bits}} ${{matrix.lto}}
